### ISSUE TITLE
Apple Push Problem

### ISSUE THREAD

**Issue by jondlew** [malliina/mobile-push#12]
Using Play Framework 2.7.4, I get the following sending a test push with a known good token and .p8 key:

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IOException: unexpected end of stream on https://api.push.apple.com/...]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:344)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:263)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:443)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:441)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Caused by: java.io.IOException: unexpected end of stream on https://api.push.apple.com/...
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:205)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
Caused by: java.io.EOFException: \n not found: limit=159 content=000018040000000000000100001000000300000001000500004000000600001f…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:231)
	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.kt:210)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:181)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)

Any ideas on what can cause this?

Thanks!

**Comment by jondlew** [comment]
Found the issue was missing "PlayAkkaHttp2Support" plugin in Play. Once that was added along with the -javaagent option to jetty-alpn-agent, push works. Thanks!
