### ISSUE TITLE
Play Server 2.5.x not starting when using this library

### ISSUE THREAD

**Issue by nkmittal** [malliina/mobile-push#9]
I added this dependency to use this lib:
libraryDependencies += "com.malliina" %% "mobile-push" % "1.7.5"

But as soon as my play app (2.5.x with scala 2.11.11) starts it fails with the following error. I believe it is causing a conflict with silhoutette lib which i use for authentication.
======================================
Exception in thread "ForkJoinPool-1-worker-1" java.lang.NoSuchMethodError: play.api.libs.json.Writes$.DefaultJodaDateWrites()Lplay/api/libs/json/DefaultWrites$DefaultJodaDateWrites$;
	at com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticator$.<init>(CookieAuthenticator.scala:91)
	at com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticator$.<clinit>(CookieAuthenticator.scala)
	at com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticatorService$$anonfun$retrieve$3.apply(CookieAuthenticator.scala:209)
	at com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticatorService$$anonfun$retrieve$3.apply(CookieAuthenticator.scala:204)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

=========================================

**Comment by malliina** [comment]
Hi, it looks to me like the versions of play-json used by version 1.7.5 of this library and play 2.5.x are not binary compatible:

- mobile-push 1.7.5 uses play-json 2.6.x
- play 2.5.x. uses play-json 2.5.x

I recommend updating to Play 2.7.x and the newest version of this library, both of which use play-json 2.7.x, or finding another combination of dependencies which are binary compatible.

**Comment by malliina** [comment]
I figure the above explanation is likely correct so I'll close this.
